[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Resource-Policy = "same-origin"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://richardslater.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = '''
      default-src 'none';
      img-src 'self' https://www.richard-slater.co.uk https://cloudfront.net https://*.cloudfront.net data: https://www.googletagmanager.com https://ws-eu.amazon-adsystem.com;
      style-src 'self' https://fonts.googleapis.com;
      script-src 'self' https://www.googletagmanager.com https://*.netlify.app/ 'sha256-+MOXilZ3WLl22hD4B8rMOzUtKoeFgn6em0SkiWmMh7k=' 'sha256-pYERp1GFTQcj76yK8huGHJtriZpv9dsW7AdV7O+VrcQ=' 'sha256-JVVDOwRpMQvCZqoDwpZ1OUJ81UoJpBxumeEHC89A9PU=' 'sha256-P04sv6Gx4G2SNlC/BLire6NlKJJRrW+WA3R+vPzVvxk=' 'sha256-RK7LdSEhpwvmYMT+Jix2uBLUXxlWBpHbN6lasgC6hv8=' 'sha256-Bw6N1XWLxWBiVK2nDwbWvrCz5xJqftvdmzhnxUbjqz0=' 'sha256-Z/yOc0e0P+QD02w8OrO7Bd5RA+T2+b+SA8PIV7nWWCo=';
      script-src-attr 'unsafe-hashes' 'sha256-nP0EI9B9ad8IoFUti2q7EQBabcE5MS5v0nkvRfUbYnM=';
      font-src data: https://fonts.gstatic.com;
      manifest-src 'none';
      connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com/;
      frame-src https://www.googletagmanager.com https://app.netlify.com/;
      report-uri https://richardslater.report-uri.com/r/d/csp/enforce;
      report-to default;
    '''
    NEL = "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
    Strict-Transport-Security = "max-age=63072000;"
    Expect-CT = "enforce, max-age=86400, report-uri=\"https://richardslater.report-uri.com/r/d/ct/enforce\""
    Expect-Staple = "max-age=31536000; report-uri=\"https://richardslater.report-uri.com/r/d/staple/enforce\""
    Permissions-Policy = '''
      accelerometer=(),
      autoplay=(),
      camera=(),
      cross-origin-isolated=(),
      display-capture=(),
      document-domain=(),
      encrypted-media=(),
      fullscreen=(),
      geolocation=(),
      gyroscope=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      publickey-credentials-get=(),
      screen-wake-lock=(),
      sync-xhr=(),
      usb=(),
      web-share=(),
      xr-spatial-tracking=()
    '''
    Feature-Policy =  '''
      geolocation 'none';
      accelerometer 'none';
      autoplay 'none';
      camera 'none';
      document-domain 'none';
      encrypted-media 'none';
      fullscreen 'none';
      gyroscope 'none';
      magnetometer 'none';
      microphone 'none';
      midi 'none';
      payment 'none';
      picture-in-picture 'none';
      sync-xhr 'none';
      usb 'none';
      xr-spatial-tracking 'none';
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Embedder-Policy = "unsafe-none; report-to=default"
    Cross-Origin-Opener-Policy = "same-origin; report-to=default"
